name: flutter_extension
description: Flutter Extension Package is collection of useful static extension methods for Flutter Widgets.
version: 0.1.1
homepage: https://github.com/ibhavikmakwana/
repository: https://github.com/ibhavikmakwana/flutter_extension

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter